global_pcodes:
  dataset: "global-pcodes"
  name: "global_pcodes.csv"
  p-code: "P-Code"
  admin: "Location"

allowed_filetypes:
  - "csv"
  - "gdb"
  - "geojson"
  - "gpkg"
  - "json"
  - "shp"
  - "topojson"
  - "xls"
  - "xlsx"

number_of_rows: 200

percent_match: 0.9

resource_size: 1073741824

org_exceptions:
  - "hot"
