# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Run tests

on:
  workflow_dispatch: # add run button in github
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install GDAL
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libgdal-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coveralls
        if [ -f test-requirements.txt ]; then pip install  --upgrade -r test-requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --junitxml=junit/test-results.xml --cov-config .coveragerc --cov-report= --cov=.
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        junit_files: .tox/*.xml
    - name: Publish in Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      if: success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: tests
